In [38]:
#importing numpy
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [39]:
#checking version of numpy
print(np.__version__)

1.26.4


In [40]:
#print type of array
print(type(arr))

<class 'numpy.ndarray'>


In [41]:
#use tuple to create numpy array
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [42]:
#0-D array
arr=np.array(42)
print(arr)
print(arr.ndim)

#1-D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.ndim)

#2-D array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)

42
0
[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2


In [43]:
#Access array elements
arr=np.array([1,2,3,4,5])
print(arr[1])

2


In [44]:
# access 2-D array
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1[1,1])
print(arr1)

6
[[1 2 3 4]
 [5 6 7 8]]


In [45]:
#Negative indexing
print(arr1[0,-1])

4


In [46]:
#NumPy array sclicing
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

#negative Sclicing
print(arr[-3:-1])

#Step
print(arr[1:5:2])

[2 3 4 5]
[5 6]
[2 4]


In [47]:
#NumPy data types
#checking the data types
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.dtype)

#numpy array shape
print(arr.shape)

#numpy array reshaping
new_arr=arr.reshape(3,3)
print(new_arr)

int32
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
#iterating array
arr=np.array([1,2,3,4,5])
for i in arr:
    print(i)

#joining array
arr1=np.array([0,1,2,3])
arr2=np.array([4,5,6,7])
arr=np.concatenate((arr1,arr2))
print(arr)

#spliting arrray
arr=np.array([1,2,3,4,5,6,7,8,9,0,3])
new_arr=np.array_split(arr,3)
print(new_arr)

#searching array
arr=np.array([1,2,3,4,5,4,6,4])
x=np.where(arr==4)
print(x)

#sorting array
print(np.sort(arr))


#filtering array
arr=np.array([41,42,43,44])
x=[True,False,True,False]
new_arr=arr[x]
print(new_arr)

1
2
3
4
5
[0 1 2 3 4 5 6 7]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([9, 0, 3])]
(array([3, 5, 7], dtype=int64),)
[1 2 3 4 4 4 5 6]
[41 43]


In [49]:
#creating filtering array
arr=np.array([41,42,43,44])
filter_arr=[]
for element in arr:
    if element>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
new_arr=arr[filter_arr]
print(filter_arr)
print(new_arr)

[False, False, True, True]
[43 44]


In [50]:
#conversion of data types
arr=np.array([1,2.5,3.5,4,5,6,7,8])
print(arr.dtype)
print(arr.astype(int))

float64
[1 2 3 4 5 6 7 8]


In [51]:
#Adding and removing element
arr=np.array([10,20,30,40])
print(np.append(arr,[50,60]))  
print(np.insert(arr,2,90))     #arr,index,element

[10 20 30 40 50 60]
[10 20 90 30 40]


In [52]:
#Aggregating functions
a=np.array([10,20,30,40,50])
   #Sum off all elements
print(np.sum(a))
   #minimum 
print(np.min(a))
   #maximum
print(np.max(a))
   #cumulative sum
print(np.cumsum(a))

150
10
50
[ 10  30  60 100 150]


In [53]:
#statistical functions
import statistics as stats
food_price=[20,30,40,50,60]
a=np.array(food_price)
#mean
print(stats.mean(a))
#median
print(stats.median(a))
#mode
print(stats.mode(a))

40
40
20
